version: '3.5'
services:
    # backend:
    #     image: acordepravida-api
    #     ports:
    #         - "5501:5501"
    database:
        image: acordepravida-mysql
        ports:
            - "3306:3036"
        environment:
            MYSQL_ROOT_PASSWORD: 123456
            MYSQL_DATABASE: AcordePraVida
            MYSQL_USER: User
            MYSQL_PASSWORD: 456789
        volumes:
            db-volume:/var/lib/mysql
volumes:
    db-volume: